databases:
  - name: snowdata-app
    databaseName: snowdata-app
    user: snowdata-app

services:
  - type: web
    name: snowdata-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snowdata-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
